# Using BPL notebooks
> BPL cells, Python magics, glyph entry and help.

## BPL kernel

Install with `pip install basedpl`, then select **BasedPL** in Jupyter's kernel menu. Write BPL directly in each code cell. Names persist between cells.

```bpl
v←⍳5
+/v
```

Shift-Tab inspects names and glyphs. `]help name` shows help; `]help name -source` shows source. See [Getting started](getting-started.ipynb) for an executable BPL tutorial.

## Python magics

Run `%load_ext basedpl.notebooks` in a Python notebook to register `%bpl` and `%%bpl`. Both share a persistent BPL workspace. To load the extension automatically in IPython and Jupyter, run `bpl-install-magic` once.

The magics evaluate in `basedpl.bpl`, so Python code that imports `bpl` shares their workspace. `%bpl ]clear` removes every name.

In [1]:
from basedpl.notebooks import create_magic

In [2]:
magic = create_magic()
magic.bpl('')

Javascript(// Based on Adám Brudzewsky's APL language bar: https://abrudz.github.io/lb
// MIT License, Copyright (c) 2011-2020 Nikolay G. Nikolov and Adam Brudzevski.
// BPL name completion, editor adapters, dark mode and overlay layout by Jeremy Howard.
((symbols, input, layout) => {
    const d = document;
    if (d.querySelector('.ngn_lb') || d.querySelector('meta[name=generator][content^=quarto]')) return;

    const {inCode, bplStart, entry, press, reset} = input(symbols, layout);
    const shortcuts = new Map(symbols.map(({glyph, shortcut}) => [glyph, shortcut]));
    let leftAlt = false, rightAlt = false;

    function textareaRect(t) {
        const mirror = d.createElement('div'), caret = d.createElement('span'), css = getComputedStyle(t), rect = t.getBoundingClientRect();
        for (const p of ['font', 'lineHeight', 'letterSpacing', 'padding', 'border', 'boxSizing', 'width', 'tabSize']) mirror.style[p] = css[p];
        Object.assign(mirror.style, {position: 'fixed', visibi

HTML(<style>/* Code fonts for the magics and the docs. scripts/prep.py copies this file to nbs/fonts.css, so edit it here. */
:root { --bpl-font: SAX2; --apl-font: BQN386; }
@font-face { font-family: SAX2; src: local("SAX2"), url("https://cdn.jsdelivr.net/gh/abrudz/SAX2@master/SAX2.ttf") format("truetype"); }
@font-face { font-family: BQN386; src: local("BQN386"), url("https://cdn.jsdelivr.net/gh/dzaima/BQN386@master/BQN386.woff2") format("woff2"); }
.bpl_out { font-family: var(--bpl-font), monospace !important; line-height: 1.05 !important; }
</style>)

Hold **left Alt/Option** and press a key from the [glyph reference](glyphs.qmd#typing-glyphs): Alt-h `←`, Alt-m `×` and Alt-u `÷`. Some glyphs take a second key, as Alt-a then `_` gives `⍶`, and Alt-6 then a digit gives a superscript. Right Option keeps its native behavior. Alt keys work in BPL input, including strings and comments.

Type a backtick followed by a BPL symbol name: `` `io `` then Tab inserts `⍳`, and `` 2`times3 `` becomes `2×3`. Suggestions appear beside the cursor as you type, including the REPL's shortcut notation: `h` means Alt-h, and `c t` means Alt-c then t. Click a suggestion or keep typing to resolve an ambiguous name. Names and aliases come from BPL's REPL catalogue.

Completion is active in `%%bpl` and `%%apl` cells and on `%bpl` lines, including `x = %bpl ...`. Ordinary Python and Markdown input is unchanged. Strings, comments and pasted text are not expanded. Tab explicitly completes an existing name. Enter accepts a unique match before the notebook's normal newline or execution action. Escape or cursor movement cancels automatic expansion.

The first `bpl` magic also adds a clickable symbol bar, based on Adám Brudzewsky's [APL language bar](https://abrudz.github.io/lb/apl). Hover over a glyph to see its names and shortcut. The `▲`/`▼` button switches between pushing the page down and overlaying it. This choice is remembered per site.

The cell magic (`%%bpl`) displays BPL output in Adám's [SAX2](https://github.com/abrudz/SAX2) APL font:

In [3]:
%%bpl
m←3 3⍴⍳9
m×10


0 10 20
30 40 50
60 70 80

Assignments are shy: the `m←` line printed nothing. The line magic returns a native array. Use `.np` to copy its values to NumPy:

In [4]:
v = %bpl 3×⍳4
v.np

array([0., 3., 6., 9.])

In [5]:
text = %bpl "APL in Python"
text.py

'APL in Python'

`.py` converts numeric atoms to Python numbers and character vectors to strings. Unkeyed numeric arrays become NumPy arrays, keyed vectors become dictionaries, and higher-rank keyed arrays become pandas DataFrames. Numeric scalars (rank-0 arrays) become zero-dimensional NumPy arrays. `.np` copies values to NumPy without labels:


In [6]:
z = %bpl m
z.np


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

To suppress a cell's output, end the last line with a `;`:


In [7]:
%%bpl
m×10;


`⎕←` displays a value explicitly, which is how you show something that would otherwise be shy:


In [8]:
%%bpl
v←2×⍳5
⎕←v


0 2 4 6 8

Convert to NumPy to use its methods:

In [9]:
a = %bpl m
a.np.sum(axis=0)


array([ 9., 12., 15.])

## Names and help

Tab completes user and system names in BPL input. Use `]help name` for comment help and `]help name -source` for BPL source:

In [10]:
%%bpl
double←{⍝ Double the argument
2×⍵}

In [11]:
%bpl ]help double

Calls: `f Y` or `X f Y`

Double the argument

In [12]:
%bpl ]help double -source

```apl
{⍝ Double the argument
2×⍵}
```

Python function objects support `f?` and `f??`. See [Python](python.ipynb#names-and-help) and [Help and introspection](introspection.ipynb).

## Errors and interruption

BPL errors raise `basedpl.BplError`. The magics display output produced before the error. Incomplete input raises a syntax error without resetting the workspace.

Interrupt a calculation with the notebook's stop button. Set a per-evaluation deadline with `bpl.timeout = seconds`. Cancellation preserves the workspace and completed assignments. Native-library calls and individual BigInt operations can delay cancellation.

BPL is an APL-derived array language, borrowing from J and BQN. See the [glyph reference](glyphs.qmd) for glyphs and system functions, and the [shared language rules](rules.qmd) for array rules.

## Other interpreters

[Dyalog sessions](dyalog.ipynb) run an independent reference interpreter. [J](j.ipynb) runs the J language, with a session class, `%%j` magics and a Jupyter kernel.

The [magics implementation](magics.ipynb) documents display, completion and workspace handling.